server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  mvc:
    path match:
      matching-strategy: ant_path_matcher
logging:
  level:
    org.hibernate.sql: debug
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: password