server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/base?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: base
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
logging:
  level:
    org.hibernate.sql: debug
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: password